apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  hostNetwork: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      otlp:
        endpoint: "http://oteld-collector.default.svc.cluster.local:4317"
        tls:
          insecure: true
      debug:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp, debug]